# Generated by Django 5.2.7 on 2025-11-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='order',
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventTicket',
        ),
    ]
