# Generated by Django 5.2.7 on 2025-10-16 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'status'), name='unique_pending_order_per_user'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('session_key', 'status'), name='unique_pending_order_per_session'),
        ),
    ]
