# Generated by Django 5.2.7 on 2025-11-19 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_eventticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.orderitem'),
        ),
    ]
