# Generated by Django 5.2.7 on 2025-10-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
