# Generated by Django 5.2.7 on 2025-11-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_eventextension_eventticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventextension',
            name='capacity',
        ),
    ]
