# Generated by Django 5.2.7 on 2025-11-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_eventextension_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventextension',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Optional total capacity', null=True),
        ),
    ]
