# Generated by Django 5.2.7 on 2025-11-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_eventextension_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventextension',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
