# Generated by Django 5.2.7 on 2025-11-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_eventextension_capacity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTicket',
        ),
    ]
